### ISSUE TITLE
cant get it working

### ISSUE THREAD

**Issue by ghost** [leszekd25/spellforce_blender_plugins#1]
Traceback (most recent call last):
  File "C:\Users\GM\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_static_msb.py", line 289, in execute
    if LoadMSBStatic(context, self.filepath) == 0:
  File "C:\Users\GM\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_static_msb.py", line 139, in LoadMSBStatic
    image = bpy.data.images.load(imagepath)
RuntimeError: Error: Cannot read 'C:\Users\GM\Desktop\figure_hero_female_head_blacklonghair 2.dds': No such file or directory

location: <unknown location>:-1

**Comment by ZarimSF** [comment]
Looks like the texture file (`figure_hero_female_head_blacklonghair 2.dds`) was not in the right place.
As stated in the README:
> textures have to be in the same directory as the .msb file (pulling them from spellforce data is enough, look for texture names that are suspiciously similar to the .msb file name)
